# Project Information
site_name: ADVANCED BIOMEDICAL COMPUTATIONAL SCIENCE
site_author: Natasha Pacheco, Ph.D.
site_description: >-
  This is a test repo to test out different layout and information options.


# Repository
repo_name: abcsFrederick/abcsFrederick.TEST.github.io
#repo_url: https://github.com/abcsFrederick/abcsFrederick.TEST.github.io
edit_uri: https://github.com/abcsFrederick/abcsFrederick.TEST.github.io/edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 ABCS

# Configuration
extra_css: 
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: docs/custom-overrides
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.tracking
  font:
    text: Roboto
  logo: images/fnl-logo-light.png
  logo_dark: images/fnl-logo-dark.png
  palette:
    - scheme: fnldark
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
    - scheme: fnl
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode


# Plugins
plugins:
  - search
  - open-in-new-tab
  - git-revision-date
  - minify:
      minify_html: true


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - About Us: index.md
  - Next-Generation Sequencing 🧬: ngs.md
  - Imaging AI 💻: imaging-ai.md
  - Statistics 📊: statistics.md
  - Training 🎓: training.md
  - Other 📚: other.md
